In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as const

In [2]:
df = pd.read_csv("solar_system.csv", na_values=["", " ", "\t"])
print(df.columns)
print(df.shape)

Index(['Attribute', 'Mercury', 'Venus', 'Earth', 'Moon', 'Mars', 'Jupiter',
       'Saturn', 'Uranus', 'Neptune', 'Pluto'],
      dtype='object')
(20, 11)

In [3]:
df = df.set_index("Attribute").T
print(df.shape)
df.index.name = "Planet"
print(df.shape)
df.reset_index(inplace=True)
print(df.shape)
df.columns.name = None
print(df.shape)

(10, 20)
(10, 20)
(10, 21)
(10, 21)

In [32]:
#5a) 20 rows and 11 columns
#5b) 11 rows 20 columns
# 5c) The first line sets the index as the attribute column, then transposes the matrix. The second line renames the index to planet, the third line changes the index back into a column and then the last line gets rid of the name
# 5d) We set Attribute as the index before we transposed, which is why it didn't normally transpose

In [5]:
print(df.columns)

Index(['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (10^6 km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

In [6]:
# 5f) 16 columns have units, 5 don't, you can see which above
print(df)

    Planet Mass (10^24kg) Diameter (km) Density (kg/m^3) Gravity (m/s^2)  \
0  Mercury          0.330          4879             5429             3.7
1    Venus           4.87         12104             5243             8.9
2    Earth           5.97         12756             5514             9.8
3     Moon          0.073          3475             3340             1.6
4     Mars          0.642          6792             3934             3.7
5  Jupiter           1898        142984             1326            23.1
6   Saturn            568        120536              687             9.0
7   Uranus           86.8         51118             1270             8.7
8  Neptune            102         49528             1638            11.0
9    Pluto         0.0130          2376             1850             0.7

  Escape Velocity (km/s) Rotation Period (hours) Length of Day (hours)  \
0                    4.3                  1407.6                4222.6
1                   10.4                 -5832.5                2802.0
2                   11.2                    23.9                  24.0
3                    2.4                   655.7                 708.7
4                    5.0                    24.6                  24.7
5                   59.5                     9.9                   9.9
6                   35.5                    10.7                  10.7
7                   21.3                   -17.2                  17.2
8                   23.5                    16.1                  16.1
9                    1.3                  -153.3                 153.3

  Distance from Sun (10^6 km) Perihelion (10^6 km)  ... Orbital Period (days)  \
0                        57.9                 46.0  ...                  88.0
1                       108.2                107.5  ...                 224.7
2                       149.6                147.1  ...                 365.2
3                       0.384                0.363  ...                  27.3
4                       228.0                206.7  ...                 687.0
5                       778.5                740.6  ...                  4331
6                      1432.0               1357.6  ...                 10747
7                      2867.0               2732.7  ...                 30589
8                      4515.0               4471.1  ...                 59800
9                      5906.4               4436.8  ...                 90560

  Orbital Velocity (km/s) Orbital Inclination (deg) Orbital Eccentricity  \
0                    47.4                       7.0                0.206
1                    35.0                       3.4                0.007
2                    29.8                       0.0                0.017
3                     1.0                       5.1                0.055
4                    24.1                       1.8                0.094
5                    13.1                       1.3                0.049
6                     9.7                       2.5                0.052
7                     6.8                       0.8                0.047
8                     5.4                       1.8                0.010
9                     4.7                      17.2                0.244

  Obliquity to Orbit (deg) Mean Temperature (C) Surface Pressure (bars)  \
0                    0.034                  167                       0
1                    177.4                  464                      92
2                     23.4                   15                       1
3                      6.7                  -20                       0
4                     25.2                  -65                    0.01
5                      3.1                 -110                 Unknown
6                     26.7                 -140                 Unknown
7                     97.8                 -195                 Unknown
8                     28.3                 -200                 Unknown
9                    119.5                 -225                 0.00001

  Number of Moons Ring System? Global Magnetic Field?
0               0           No                    Yes
1               0           No                     No
2               1           No                    Yes
3               0           No                     No
4               2           No                     No
5              95          Yes                    Yes
6             274          Yes                    Yes
7              28          Yes                    Yes
8              16          Yes                    Yes
9               5           No                Unknown

[10 rows x 21 columns]

In [7]:
df.dtypes

Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object

In [8]:
for col in df.columns:
    print(df[col].apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Planet, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mass (10^24kg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Diameter (km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Density (kg/m^3), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Gravity (m/s^2), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Escape Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Rotation Period (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Length of Day (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Distance from Sun (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Perihelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Aphelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Period (days), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Inclination (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Eccentricity, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Obliquity to Orbit (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mean Temperature (C), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Surface Pressure (bars), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Number of Moons, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Ring System?, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Global Magnetic Field?, dtype: object

In [9]:
# 2.1.2a) They are all string types
# 2.1.2b) If you store all the numeric values as strings then you can't do math with them, which becomes a problem.

In [10]:
for col in df.columns:
    if col != "Planet" and col != "Ring System?" and col != "Global Magnetic Field?":
        df[col] = pd.to_numeric(df[col], errors="coerce")

In [11]:
df.dtypes

Planet                          object
Mass (10^24kg)                 float64
Diameter (km)                    int64
Density (kg/m^3)                 int64
Gravity (m/s^2)                float64
Escape Velocity (km/s)         float64
Rotation Period (hours)        float64
Length of Day (hours)          float64
Distance from Sun (10^6 km)    float64
Perihelion (10^6 km)           float64
Aphelion (10^6 km)             float64
Orbital Period (days)          float64
Orbital Velocity (km/s)        float64
Orbital Inclination (deg)      float64
Orbital Eccentricity           float64
Obliquity to Orbit (deg)       float64
Mean Temperature (C)             int64
Surface Pressure (bars)        float64
Number of Moons                  int64
Ring System?                    object
Global Magnetic Field?          object
dtype: object

In [28]:
# 2.1.3a) There are now objects, float64s, and int64s
# 2.1.3b) Objects are strings and booleans, floats is a data type that stores decimals, and ints are whole numbers
# 2.1.3c) The columns Planet, Ring System? and Global Magnetic Field? are still objects b/c they do not contain number values

In [13]:
unit_list = [1e24 * u.kg, u.km, u.kg / (u.m**3), u.m / (u.s**2), u.km / u.s, u.h, u.h, (1e6/1.496e8) * u.AU, (1e6/1.496e8) * u.AU, (1e6/1.496e8) * u.AU, 1/365 * u.yr, u.km / u.s, u.deg, u.deg, u.deg_C, 100000 * u.Pa]
renaming_list = ["Mass (kg)", "Distance from Sun (AU)", "Perihelion (AU)", "Aphelion (AU)", "Orbital Period (Years)", "Surface Pressure (Pascals)"]
def attach_units():
    unit_i = 0
    skip_index = {0, 14, 18, 19, 20}
    rename_index = {1, 8, 9, 10, 11, 17}
    for i, col in enumerate(df.columns):
        if i not in skip_index:
            numeric = pd.to_numeric(df[col], errors="coerce")
            df[col] = numeric.to_numpy() * unit_list[unit_i]
            unit_i += 1
    mapping = {
        df.columns[i]: renaming_list[k]
        for k, i in enumerate(sorted(rename_index))
    }
    df.rename(columns=mapping, inplace=True)

In [14]:
attach_units()

In [15]:
df

,Planet,Mass (kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (AU),Perihelion (AU),...,Orbital Period (Years),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (Pascals),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,3.300000e+23,4879.0,5429.0,3.7,4.3,1407.6,4222.6,0.387032,0.307487,...,0.241096,47.4,7.0,0.206,0.034,167.0,0.0,0,No,Yes
1,Venus,4.870000e+24,12104.0,5243.0,8.9,10.4,-5832.5,2802.0,0.723262,0.718583,...,0.615616,35.0,3.4,0.007,177.400,464.0,9200000.0,0,No,No
2,Earth,5.970000e+24,12756.0,5514.0,9.8,11.2,23.9,24.0,1.000000,0.983289,...,1.000548,29.8,0.0,0.017,23.400,15.0,100000.0,1,No,Yes
3,Moon,7.300000e+22,3475.0,3340.0,1.6,2.4,655.7,708.7,0.002567,0.002426,...,0.074795,1.0,5.1,0.055,6.700,-20.0,0.0,0,No,No
4,Mars,6.420000e+23,6792.0,3934.0,3.7,5.0,24.6,24.7,1.524064,1.381684,...,1.882192,24.1,1.8,0.094,25.200,-65.0,1000.0,2,No,No
5,Jupiter,1.898000e+27,142984.0,1326.0,23.1,59.5,9.9,9.9,5.203877,4.950535,...,11.865753,13.1,1.3,0.049,3.100,-110.0,NaN,95,Yes,Yes
6,Saturn,5.680000e+26,120536.0,687.0,9.0,35.5,10.7,10.7,9.572193,9.074866,...,29.443836,9.7,2.5,0.052,26.700,-140.0,NaN,274,Yes,Yes
7,Uranus,8.680000e+25,51118.0,1270.0,8.7,21.3,-17.2,17.2,19.164439,18.266711,...,83.805479,6.8,0.8,0.047,97.800,-195.0,NaN,28,Yes,Yes
8,Neptune,1.020000e+26,49528.0,1638.0,11.0,23.5,16.1,16.1,30.180481,29.887032,...,163.835616,5.4,1.8,0.010,28.300,-200.0,NaN,16,Yes,Yes
9,Pluto,1.300000e+22,2376.0,1850.0,0.7,1.3,-153.3,153.3,39.481283,29.657754,...,248.109589,4.7,17.2,0.244,119.500,-225.0,1.0,5,No,Unknown

In [29]:
# I just combined multiple parts of the homework into the above function.
# I appended units to all of the columns that didnt have one
#after i just printed them all
# I converted the orbital period to years and orbital distance from AU to km

In [30]:
df.columns

Index(['Planet', 'Mass (kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (AU)', 'Perihelion (AU)',
       'Aphelion (AU)', 'Semi-Major Axis (AU)', 'Orbital Period (Years)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (Pascals)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?'],
      dtype='object')

In [31]:
df

,Planet,Mass (kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (AU),Perihelion (AU),...,Orbital Period (Years),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (Pascals),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,3.300000e+23,4879.0,5429.0,3.7,4.3,1407.6,4222.6,0.387032,0.307487,...,0.241096,47.4,7.0,0.206,0.034,167.0,0.0,0,No,Yes
1,Venus,4.870000e+24,12104.0,5243.0,8.9,10.4,-5832.5,2802.0,0.723262,0.718583,...,0.615616,35.0,3.4,0.007,177.400,464.0,9200000.0,0,No,No
2,Earth,5.970000e+24,12756.0,5514.0,9.8,11.2,23.9,24.0,1.000000,0.983289,...,1.000548,29.8,0.0,0.017,23.400,15.0,100000.0,1,No,Yes
3,Moon,7.300000e+22,3475.0,3340.0,1.6,2.4,655.7,708.7,0.002567,0.002426,...,0.074795,1.0,5.1,0.055,6.700,-20.0,0.0,0,No,No
4,Mars,6.420000e+23,6792.0,3934.0,3.7,5.0,24.6,24.7,1.524064,1.381684,...,1.882192,24.1,1.8,0.094,25.200,-65.0,1000.0,2,No,No
5,Jupiter,1.898000e+27,142984.0,1326.0,23.1,59.5,9.9,9.9,5.203877,4.950535,...,11.865753,13.1,1.3,0.049,3.100,-110.0,NaN,95,Yes,Yes
6,Saturn,5.680000e+26,120536.0,687.0,9.0,35.5,10.7,10.7,9.572193,9.074866,...,29.443836,9.7,2.5,0.052,26.700,-140.0,NaN,274,Yes,Yes
7,Uranus,8.680000e+25,51118.0,1270.0,8.7,21.3,-17.2,17.2,19.164439,18.266711,...,83.805479,6.8,0.8,0.047,97.800,-195.0,NaN,28,Yes,Yes
8,Neptune,1.020000e+26,49528.0,1638.0,11.0,23.5,16.1,16.1,30.180481,29.887032,...,163.835616,5.4,1.8,0.010,28.300,-200.0,NaN,16,Yes,Yes
9,Pluto,1.300000e+22,2376.0,1850.0,0.7,1.3,-153.3,153.3,39.481283,29.657754,...,248.109589,4.7,17.2,0.244,119.500,-225.0,1.0,5,No,Unknown

In [19]:
axis_list = []
for peri, aphi in zip(df["Perihelion (AU)"], df["Aphelion (AU)"]):
    value = (peri.value + aphi.value) / 2
    axis_list.append(value)
df.insert(11, "Semi-Major Axis (AU)", axis_list)
df["Semi-Major Axis (AU)"]

0     0.387032
1     0.723262
2     1.000000
3     0.002570
4     1.524064
5     5.203877
6     9.572527
7    19.164773
8    30.180481
9    39.480949
Name: Semi-Major Axis (AU), dtype: float64

In [20]:
print(f"The period of Neptune is {df.at[8, "Orbital Period (Years)"]:.4f}.")

The period of Neptune is 163.8356 yr.

In [21]:
# AU is the distance of the earths semi major axis
print(const.au)

  Name   = Astronomical Unit
  Value  = 149597870700.0
  Uncertainty  = 0.0
  Unit  = m
  Reference = IAU 2012 Resolution B2

In [22]:
# There are 1.5e8 km in an AU

In [23]:
print(df)

    Planet     Mass (kg)  Diameter (km)  Density (kg/m^3)  Gravity (m/s^2)  \
0  Mercury  3.300000e+23         4879.0            5429.0              3.7
1    Venus  4.870000e+24        12104.0            5243.0              8.9
2    Earth  5.970000e+24        12756.0            5514.0              9.8
3     Moon  7.300000e+22         3475.0            3340.0              1.6
4     Mars  6.420000e+23         6792.0            3934.0              3.7
5  Jupiter  1.898000e+27       142984.0            1326.0             23.1
6   Saturn  5.680000e+26       120536.0             687.0              9.0
7   Uranus  8.680000e+25        51118.0            1270.0              8.7
8  Neptune  1.020000e+26        49528.0            1638.0             11.0
9    Pluto  1.300000e+22         2376.0            1850.0              0.7

   Escape Velocity (km/s)  Rotation Period (hours)  Length of Day (hours)  \
0                     4.3                   1407.6                 4222.6
1                    10.4                  -5832.5                 2802.0
2                    11.2                     23.9                   24.0
3                     2.4                    655.7                  708.7
4                     5.0                     24.6                   24.7
5                    59.5                      9.9                    9.9
6                    35.5                     10.7                   10.7
7                    21.3                    -17.2                   17.2
8                    23.5                     16.1                   16.1
9                     1.3                   -153.3                  153.3

   Distance from Sun (AU)  Perihelion (AU)  ...  Orbital Period (Years)  \
0                0.387032         0.307487  ...                0.241096
1                0.723262         0.718583  ...                0.615616
2                1.000000         0.983289  ...                1.000548
3                0.002567         0.002426  ...                0.074795
4                1.524064         1.381684  ...                1.882192
5                5.203877         4.950535  ...               11.865753
6                9.572193         9.074866  ...               29.443836
7               19.164439        18.266711  ...               83.805479
8               30.180481        29.887032  ...              163.835616
9               39.481283        29.657754  ...              248.109589

   Orbital Velocity (km/s)  Orbital Inclination (deg)  Orbital Eccentricity  \
0                     47.4                        7.0                 0.206
1                     35.0                        3.4                 0.007
2                     29.8                        0.0                 0.017
3                      1.0                        5.1                 0.055
4                     24.1                        1.8                 0.094
5                     13.1                        1.3                 0.049
6                      9.7                        2.5                 0.052
7                      6.8                        0.8                 0.047
8                      5.4                        1.8                 0.010
9                      4.7                       17.2                 0.244

   Obliquity to Orbit (deg)  Mean Temperature (C)  Surface Pressure (Pascals)  \
0                     0.034                 167.0                         0.0
1                   177.400                 464.0                   9200000.0
2                    23.400                  15.0                    100000.0
3                     6.700                 -20.0                         0.0
4                    25.200                 -65.0                      1000.0
5                     3.100                -110.0                         NaN
6                    26.700                -140.0                         NaN
7                    97.800                -195.0                         NaN
8                    28.300                -200.0                         NaN
9                   119.500                -225.0                         1.0

   Number of Moons  Ring System?  Global Magnetic Field?
0                0            No                     Yes
1                0            No                      No
2                1            No                     Yes
3                0            No                      No
4                2            No                      No
5               95           Yes                     Yes
6              274           Yes                     Yes
7               28           Yes                     Yes
8               16           Yes                     Yes
9                5            No                 Unknown

[10 rows x 22 columns]

In [24]:
df

,Planet,Mass (kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (AU),Perihelion (AU),...,Orbital Period (Years),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (Pascals),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,3.300000e+23,4879.0,5429.0,3.7,4.3,1407.6,4222.6,0.387032,0.307487,...,0.241096,47.4,7.0,0.206,0.034,167.0,0.0,0,No,Yes
1,Venus,4.870000e+24,12104.0,5243.0,8.9,10.4,-5832.5,2802.0,0.723262,0.718583,...,0.615616,35.0,3.4,0.007,177.400,464.0,9200000.0,0,No,No
2,Earth,5.970000e+24,12756.0,5514.0,9.8,11.2,23.9,24.0,1.000000,0.983289,...,1.000548,29.8,0.0,0.017,23.400,15.0,100000.0,1,No,Yes
3,Moon,7.300000e+22,3475.0,3340.0,1.6,2.4,655.7,708.7,0.002567,0.002426,...,0.074795,1.0,5.1,0.055,6.700,-20.0,0.0,0,No,No
4,Mars,6.420000e+23,6792.0,3934.0,3.7,5.0,24.6,24.7,1.524064,1.381684,...,1.882192,24.1,1.8,0.094,25.200,-65.0,1000.0,2,No,No
5,Jupiter,1.898000e+27,142984.0,1326.0,23.1,59.5,9.9,9.9,5.203877,4.950535,...,11.865753,13.1,1.3,0.049,3.100,-110.0,NaN,95,Yes,Yes
6,Saturn,5.680000e+26,120536.0,687.0,9.0,35.5,10.7,10.7,9.572193,9.074866,...,29.443836,9.7,2.5,0.052,26.700,-140.0,NaN,274,Yes,Yes
7,Uranus,8.680000e+25,51118.0,1270.0,8.7,21.3,-17.2,17.2,19.164439,18.266711,...,83.805479,6.8,0.8,0.047,97.800,-195.0,NaN,28,Yes,Yes
8,Neptune,1.020000e+26,49528.0,1638.0,11.0,23.5,16.1,16.1,30.180481,29.887032,...,163.835616,5.4,1.8,0.010,28.300,-200.0,NaN,16,Yes,Yes
9,Pluto,1.300000e+22,2376.0,1850.0,0.7,1.3,-153.3,153.3,39.481283,29.657754,...,248.109589,4.7,17.2,0.244,119.500,-225.0,1.0,5,No,Unknown

In [25]:
df.dtypes

Planet                         object
Mass (kg)                     float64
Diameter (km)                 float64
Density (kg/m^3)              float64
Gravity (m/s^2)               float64
Escape Velocity (km/s)        float64
Rotation Period (hours)       float64
Length of Day (hours)         float64
Distance from Sun (AU)        float64
Perihelion (AU)               float64
Aphelion (AU)                 float64
Semi-Major Axis (AU)          float64
Orbital Period (Years)        float64
Orbital Velocity (km/s)       float64
Orbital Inclination (deg)     float64
Orbital Eccentricity          float64
Obliquity to Orbit (deg)      float64
Mean Temperature (C)          float64
Surface Pressure (Pascals)    float64
Number of Moons                 int64
Ring System?                   object
Global Magnetic Field?         object
dtype: object

In [26]:
from astropy.table import QTable
QTable.from_pandas(df).write("units.ecsv", format="ascii.ecsv", overwrite=True)
# I had to use a different file type b/c a normal csv file wasnt working for some rzn